# Site settings
title: "Kushagra Garg"
description: "Researcher in quantum algorithms"
url: "https://kushargs.github.io"
baseurl: ""
author: "Kushagra Garg"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  

# Collections
collections:
  notes:
    output: true
    permalink: /notes/:name/

# Permalinks
permalink: /blog/:year/:month/:day/:title/

# Custom variables
github_username: kushargs
scholar_link: "https://scholar.google.com/citations?user=yourid"
email: "kushargsg@gmail.com"
